server:
  port: ${PORT:8000}
spring:
  application:
    name: user-api
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}