spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-api-list-users
          uri: lb://USER-API
          predicates:
            - Path=/api/users
            - Method=GET

        - id: user-api-get-user
          uri: lb://USER-API
          predicates:
            - Path=/api/users/{id}
          filters:
            - RewritePath=/(?<id>.*), /${id}

        - id: payroll-api
          uri: lb://PAYROLL-API
          predicates:
            - Path=/api/payments
            - Method=POST
#    discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
server:
  port: ${PORT:8765}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}